// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module mergeClusters1 (
        ap_ready,
        iphi1,
        icet1,
        ieta2,
        iphi2,
        icet2,
        ap_return_0,
        ap_return_1,
        ap_return_2
);


output   ap_ready;
input  [2:0] iphi1;
input  [15:0] icet1;
input  [2:0] ieta2;
input  [2:0] iphi2;
input  [15:0] icet2;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;

wire   [0:0] tmp_s_fu_72_p2;
wire   [15:0] tmp_1_fu_78_p2;
wire   [0:0] tmp_fu_66_p2;
wire   [15:0] p_tmp_s_fu_84_p3;
wire   [15:0] ieta2_cast_fu_62_p1;
wire   [15:0] iphi2_cast2_fu_58_p1;
wire   [15:0] cet2_write_assign_fu_92_p3;

assign ap_ready = 1'b1;

assign ap_return_0 = ieta2_cast_fu_62_p1;

assign ap_return_1 = iphi2_cast2_fu_58_p1;

assign ap_return_2 = cet2_write_assign_fu_92_p3;

assign cet2_write_assign_fu_92_p3 = ((tmp_fu_66_p2[0:0] === 1'b1) ? p_tmp_s_fu_84_p3 : icet2);

assign ieta2_cast_fu_62_p1 = ieta2;

assign iphi2_cast2_fu_58_p1 = iphi2;

assign p_tmp_s_fu_84_p3 = ((tmp_s_fu_72_p2[0:0] === 1'b1) ? 16'd0 : tmp_1_fu_78_p2);

assign tmp_1_fu_78_p2 = (icet2 + icet1);

assign tmp_fu_66_p2 = ((iphi1 == iphi2) ? 1'b1 : 1'b0);

assign tmp_s_fu_72_p2 = ((icet1 > icet2) ? 1'b1 : 1'b0);

endmodule //mergeClusters1
