-- Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2018.2 (lin64) Build 2258646 Thu Jun 14 20:02:38 MDT 2018
-- Date        : Tue Nov 27 16:50:09 2018
-- Host        : moonraker.cern.ch running 64-bit Scientific Linux CERN SLC release 6.10 (Carbon)
-- Command     : write_vhdl -force -mode synth_stub
--               /data/alex/repos/APx_Gen0_Algo/VivadoHls/null_algo/vivado_hls/ip/algo_top_stub.vhd
-- Design      : algo_top
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7vx690tffg1927-2
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity algo_top is
  Port ( 
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    ap_start : in STD_LOGIC;
    ap_done : out STD_LOGIC;
    ap_idle : out STD_LOGIC;
    ap_ready : out STD_LOGIC;
    link_in_00_TVALID : in STD_LOGIC;
    link_in_01_TVALID : in STD_LOGIC;
    link_in_02_TVALID : in STD_LOGIC;
    link_in_03_TVALID : in STD_LOGIC;
    link_in_04_TVALID : in STD_LOGIC;
    link_in_05_TVALID : in STD_LOGIC;
    link_in_06_TVALID : in STD_LOGIC;
    link_in_07_TVALID : in STD_LOGIC;
    link_in_08_TVALID : in STD_LOGIC;
    link_in_09_TVALID : in STD_LOGIC;
    link_in_10_TVALID : in STD_LOGIC;
    link_in_11_TVALID : in STD_LOGIC;
    link_in_12_TVALID : in STD_LOGIC;
    link_in_13_TVALID : in STD_LOGIC;
    link_in_14_TVALID : in STD_LOGIC;
    link_in_15_TVALID : in STD_LOGIC;
    link_in_16_TVALID : in STD_LOGIC;
    link_in_17_TVALID : in STD_LOGIC;
    link_in_18_TVALID : in STD_LOGIC;
    link_in_19_TVALID : in STD_LOGIC;
    link_in_20_TVALID : in STD_LOGIC;
    link_in_21_TVALID : in STD_LOGIC;
    link_in_22_TVALID : in STD_LOGIC;
    link_in_23_TVALID : in STD_LOGIC;
    link_in_24_TVALID : in STD_LOGIC;
    link_in_25_TVALID : in STD_LOGIC;
    link_in_26_TVALID : in STD_LOGIC;
    link_in_27_TVALID : in STD_LOGIC;
    link_in_28_TVALID : in STD_LOGIC;
    link_in_29_TVALID : in STD_LOGIC;
    link_in_30_TVALID : in STD_LOGIC;
    link_in_31_TVALID : in STD_LOGIC;
    link_in_32_TVALID : in STD_LOGIC;
    link_in_33_TVALID : in STD_LOGIC;
    link_in_34_TVALID : in STD_LOGIC;
    link_in_35_TVALID : in STD_LOGIC;
    link_in_36_TVALID : in STD_LOGIC;
    link_in_37_TVALID : in STD_LOGIC;
    link_in_38_TVALID : in STD_LOGIC;
    link_in_39_TVALID : in STD_LOGIC;
    link_in_40_TVALID : in STD_LOGIC;
    link_in_41_TVALID : in STD_LOGIC;
    link_in_42_TVALID : in STD_LOGIC;
    link_in_43_TVALID : in STD_LOGIC;
    link_in_44_TVALID : in STD_LOGIC;
    link_in_45_TVALID : in STD_LOGIC;
    link_in_46_TVALID : in STD_LOGIC;
    link_in_47_TVALID : in STD_LOGIC;
    link_out_00_TREADY : in STD_LOGIC;
    link_out_01_TREADY : in STD_LOGIC;
    link_out_02_TREADY : in STD_LOGIC;
    link_out_03_TREADY : in STD_LOGIC;
    link_out_04_TREADY : in STD_LOGIC;
    link_out_05_TREADY : in STD_LOGIC;
    link_out_06_TREADY : in STD_LOGIC;
    link_out_07_TREADY : in STD_LOGIC;
    link_out_08_TREADY : in STD_LOGIC;
    link_out_09_TREADY : in STD_LOGIC;
    link_out_10_TREADY : in STD_LOGIC;
    link_out_11_TREADY : in STD_LOGIC;
    link_out_12_TREADY : in STD_LOGIC;
    link_out_13_TREADY : in STD_LOGIC;
    link_out_14_TREADY : in STD_LOGIC;
    link_out_15_TREADY : in STD_LOGIC;
    link_out_16_TREADY : in STD_LOGIC;
    link_out_17_TREADY : in STD_LOGIC;
    link_out_18_TREADY : in STD_LOGIC;
    link_out_19_TREADY : in STD_LOGIC;
    link_out_20_TREADY : in STD_LOGIC;
    link_out_21_TREADY : in STD_LOGIC;
    link_out_22_TREADY : in STD_LOGIC;
    link_out_23_TREADY : in STD_LOGIC;
    link_out_24_TREADY : in STD_LOGIC;
    link_out_25_TREADY : in STD_LOGIC;
    link_out_26_TREADY : in STD_LOGIC;
    link_out_27_TREADY : in STD_LOGIC;
    link_out_28_TREADY : in STD_LOGIC;
    link_out_29_TREADY : in STD_LOGIC;
    link_out_30_TREADY : in STD_LOGIC;
    link_out_31_TREADY : in STD_LOGIC;
    link_out_32_TREADY : in STD_LOGIC;
    link_out_33_TREADY : in STD_LOGIC;
    link_out_34_TREADY : in STD_LOGIC;
    link_out_35_TREADY : in STD_LOGIC;
    link_out_36_TREADY : in STD_LOGIC;
    link_out_37_TREADY : in STD_LOGIC;
    link_out_38_TREADY : in STD_LOGIC;
    link_out_39_TREADY : in STD_LOGIC;
    link_out_40_TREADY : in STD_LOGIC;
    link_out_41_TREADY : in STD_LOGIC;
    link_out_42_TREADY : in STD_LOGIC;
    link_out_43_TREADY : in STD_LOGIC;
    link_out_44_TREADY : in STD_LOGIC;
    link_out_45_TREADY : in STD_LOGIC;
    link_out_46_TREADY : in STD_LOGIC;
    link_out_47_TREADY : in STD_LOGIC;
    link_in_00_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_00_TREADY : out STD_LOGIC;
    link_in_00_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_01_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_01_TREADY : out STD_LOGIC;
    link_in_01_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_02_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_02_TREADY : out STD_LOGIC;
    link_in_02_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_03_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_03_TREADY : out STD_LOGIC;
    link_in_03_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_04_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_04_TREADY : out STD_LOGIC;
    link_in_04_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_05_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_05_TREADY : out STD_LOGIC;
    link_in_05_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_06_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_06_TREADY : out STD_LOGIC;
    link_in_06_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_07_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_07_TREADY : out STD_LOGIC;
    link_in_07_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_08_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_08_TREADY : out STD_LOGIC;
    link_in_08_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_09_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_09_TREADY : out STD_LOGIC;
    link_in_09_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_10_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_10_TREADY : out STD_LOGIC;
    link_in_10_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_11_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_11_TREADY : out STD_LOGIC;
    link_in_11_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_12_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_12_TREADY : out STD_LOGIC;
    link_in_12_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_13_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_13_TREADY : out STD_LOGIC;
    link_in_13_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_14_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_14_TREADY : out STD_LOGIC;
    link_in_14_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_15_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_15_TREADY : out STD_LOGIC;
    link_in_15_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_16_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_16_TREADY : out STD_LOGIC;
    link_in_16_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_17_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_17_TREADY : out STD_LOGIC;
    link_in_17_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_18_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_18_TREADY : out STD_LOGIC;
    link_in_18_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_19_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_19_TREADY : out STD_LOGIC;
    link_in_19_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_20_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_20_TREADY : out STD_LOGIC;
    link_in_20_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_21_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_21_TREADY : out STD_LOGIC;
    link_in_21_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_22_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_22_TREADY : out STD_LOGIC;
    link_in_22_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_23_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_23_TREADY : out STD_LOGIC;
    link_in_23_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_24_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_24_TREADY : out STD_LOGIC;
    link_in_24_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_25_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_25_TREADY : out STD_LOGIC;
    link_in_25_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_26_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_26_TREADY : out STD_LOGIC;
    link_in_26_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_27_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_27_TREADY : out STD_LOGIC;
    link_in_27_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_28_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_28_TREADY : out STD_LOGIC;
    link_in_28_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_29_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_29_TREADY : out STD_LOGIC;
    link_in_29_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_30_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_30_TREADY : out STD_LOGIC;
    link_in_30_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_31_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_31_TREADY : out STD_LOGIC;
    link_in_31_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_32_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_32_TREADY : out STD_LOGIC;
    link_in_32_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_33_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_33_TREADY : out STD_LOGIC;
    link_in_33_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_34_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_34_TREADY : out STD_LOGIC;
    link_in_34_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_35_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_35_TREADY : out STD_LOGIC;
    link_in_35_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_36_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_36_TREADY : out STD_LOGIC;
    link_in_36_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_37_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_37_TREADY : out STD_LOGIC;
    link_in_37_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_38_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_38_TREADY : out STD_LOGIC;
    link_in_38_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_39_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_39_TREADY : out STD_LOGIC;
    link_in_39_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_40_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_40_TREADY : out STD_LOGIC;
    link_in_40_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_41_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_41_TREADY : out STD_LOGIC;
    link_in_41_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_42_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_42_TREADY : out STD_LOGIC;
    link_in_42_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_43_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_43_TREADY : out STD_LOGIC;
    link_in_43_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_44_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_44_TREADY : out STD_LOGIC;
    link_in_44_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_45_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_45_TREADY : out STD_LOGIC;
    link_in_45_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_46_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_46_TREADY : out STD_LOGIC;
    link_in_46_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_in_47_TDATA : in STD_LOGIC_VECTOR ( 63 downto 0 );
    link_in_47_TREADY : out STD_LOGIC;
    link_in_47_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_00_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_00_TVALID : out STD_LOGIC;
    link_out_00_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_01_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_01_TVALID : out STD_LOGIC;
    link_out_01_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_02_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_02_TVALID : out STD_LOGIC;
    link_out_02_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_03_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_03_TVALID : out STD_LOGIC;
    link_out_03_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_04_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_04_TVALID : out STD_LOGIC;
    link_out_04_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_05_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_05_TVALID : out STD_LOGIC;
    link_out_05_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_06_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_06_TVALID : out STD_LOGIC;
    link_out_06_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_07_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_07_TVALID : out STD_LOGIC;
    link_out_07_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_08_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_08_TVALID : out STD_LOGIC;
    link_out_08_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_09_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_09_TVALID : out STD_LOGIC;
    link_out_09_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_10_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_10_TVALID : out STD_LOGIC;
    link_out_10_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_11_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_11_TVALID : out STD_LOGIC;
    link_out_11_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_12_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_12_TVALID : out STD_LOGIC;
    link_out_12_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_13_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_13_TVALID : out STD_LOGIC;
    link_out_13_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_14_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_14_TVALID : out STD_LOGIC;
    link_out_14_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_15_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_15_TVALID : out STD_LOGIC;
    link_out_15_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_16_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_16_TVALID : out STD_LOGIC;
    link_out_16_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_17_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_17_TVALID : out STD_LOGIC;
    link_out_17_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_18_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_18_TVALID : out STD_LOGIC;
    link_out_18_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_19_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_19_TVALID : out STD_LOGIC;
    link_out_19_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_20_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_20_TVALID : out STD_LOGIC;
    link_out_20_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_21_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_21_TVALID : out STD_LOGIC;
    link_out_21_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_22_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_22_TVALID : out STD_LOGIC;
    link_out_22_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_23_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_23_TVALID : out STD_LOGIC;
    link_out_23_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_24_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_24_TVALID : out STD_LOGIC;
    link_out_24_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_25_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_25_TVALID : out STD_LOGIC;
    link_out_25_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_26_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_26_TVALID : out STD_LOGIC;
    link_out_26_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_27_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_27_TVALID : out STD_LOGIC;
    link_out_27_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_28_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_28_TVALID : out STD_LOGIC;
    link_out_28_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_29_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_29_TVALID : out STD_LOGIC;
    link_out_29_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_30_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_30_TVALID : out STD_LOGIC;
    link_out_30_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_31_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_31_TVALID : out STD_LOGIC;
    link_out_31_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_32_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_32_TVALID : out STD_LOGIC;
    link_out_32_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_33_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_33_TVALID : out STD_LOGIC;
    link_out_33_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_34_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_34_TVALID : out STD_LOGIC;
    link_out_34_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_35_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_35_TVALID : out STD_LOGIC;
    link_out_35_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_36_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_36_TVALID : out STD_LOGIC;
    link_out_36_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_37_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_37_TVALID : out STD_LOGIC;
    link_out_37_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_38_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_38_TVALID : out STD_LOGIC;
    link_out_38_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_39_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_39_TVALID : out STD_LOGIC;
    link_out_39_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_40_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_40_TVALID : out STD_LOGIC;
    link_out_40_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_41_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_41_TVALID : out STD_LOGIC;
    link_out_41_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_42_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_42_TVALID : out STD_LOGIC;
    link_out_42_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_43_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_43_TVALID : out STD_LOGIC;
    link_out_43_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_44_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_44_TVALID : out STD_LOGIC;
    link_out_44_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_45_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_45_TVALID : out STD_LOGIC;
    link_out_45_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_46_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_46_TVALID : out STD_LOGIC;
    link_out_46_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    link_out_47_TDATA : out STD_LOGIC_VECTOR ( 63 downto 0 );
    link_out_47_TVALID : out STD_LOGIC;
    link_out_47_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 )
  );

end algo_top;

architecture stub of algo_top is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "ap_clk,ap_rst_n,ap_start,ap_done,ap_idle,ap_ready,link_in_00_TVALID,link_in_01_TVALID,link_in_02_TVALID,link_in_03_TVALID,link_in_04_TVALID,link_in_05_TVALID,link_in_06_TVALID,link_in_07_TVALID,link_in_08_TVALID,link_in_09_TVALID,link_in_10_TVALID,link_in_11_TVALID,link_in_12_TVALID,link_in_13_TVALID,link_in_14_TVALID,link_in_15_TVALID,link_in_16_TVALID,link_in_17_TVALID,link_in_18_TVALID,link_in_19_TVALID,link_in_20_TVALID,link_in_21_TVALID,link_in_22_TVALID,link_in_23_TVALID,link_in_24_TVALID,link_in_25_TVALID,link_in_26_TVALID,link_in_27_TVALID,link_in_28_TVALID,link_in_29_TVALID,link_in_30_TVALID,link_in_31_TVALID,link_in_32_TVALID,link_in_33_TVALID,link_in_34_TVALID,link_in_35_TVALID,link_in_36_TVALID,link_in_37_TVALID,link_in_38_TVALID,link_in_39_TVALID,link_in_40_TVALID,link_in_41_TVALID,link_in_42_TVALID,link_in_43_TVALID,link_in_44_TVALID,link_in_45_TVALID,link_in_46_TVALID,link_in_47_TVALID,link_out_00_TREADY,link_out_01_TREADY,link_out_02_TREADY,link_out_03_TREADY,link_out_04_TREADY,link_out_05_TREADY,link_out_06_TREADY,link_out_07_TREADY,link_out_08_TREADY,link_out_09_TREADY,link_out_10_TREADY,link_out_11_TREADY,link_out_12_TREADY,link_out_13_TREADY,link_out_14_TREADY,link_out_15_TREADY,link_out_16_TREADY,link_out_17_TREADY,link_out_18_TREADY,link_out_19_TREADY,link_out_20_TREADY,link_out_21_TREADY,link_out_22_TREADY,link_out_23_TREADY,link_out_24_TREADY,link_out_25_TREADY,link_out_26_TREADY,link_out_27_TREADY,link_out_28_TREADY,link_out_29_TREADY,link_out_30_TREADY,link_out_31_TREADY,link_out_32_TREADY,link_out_33_TREADY,link_out_34_TREADY,link_out_35_TREADY,link_out_36_TREADY,link_out_37_TREADY,link_out_38_TREADY,link_out_39_TREADY,link_out_40_TREADY,link_out_41_TREADY,link_out_42_TREADY,link_out_43_TREADY,link_out_44_TREADY,link_out_45_TREADY,link_out_46_TREADY,link_out_47_TREADY,link_in_00_TDATA[63:0],link_in_00_TREADY,link_in_00_TLAST[0:0],link_in_01_TDATA[63:0],link_in_01_TREADY,link_in_01_TLAST[0:0],link_in_02_TDATA[63:0],link_in_02_TREADY,link_in_02_TLAST[0:0],link_in_03_TDATA[63:0],link_in_03_TREADY,link_in_03_TLAST[0:0],link_in_04_TDATA[63:0],link_in_04_TREADY,link_in_04_TLAST[0:0],link_in_05_TDATA[63:0],link_in_05_TREADY,link_in_05_TLAST[0:0],link_in_06_TDATA[63:0],link_in_06_TREADY,link_in_06_TLAST[0:0],link_in_07_TDATA[63:0],link_in_07_TREADY,link_in_07_TLAST[0:0],link_in_08_TDATA[63:0],link_in_08_TREADY,link_in_08_TLAST[0:0],link_in_09_TDATA[63:0],link_in_09_TREADY,link_in_09_TLAST[0:0],link_in_10_TDATA[63:0],link_in_10_TREADY,link_in_10_TLAST[0:0],link_in_11_TDATA[63:0],link_in_11_TREADY,link_in_11_TLAST[0:0],link_in_12_TDATA[63:0],link_in_12_TREADY,link_in_12_TLAST[0:0],link_in_13_TDATA[63:0],link_in_13_TREADY,link_in_13_TLAST[0:0],link_in_14_TDATA[63:0],link_in_14_TREADY,link_in_14_TLAST[0:0],link_in_15_TDATA[63:0],link_in_15_TREADY,link_in_15_TLAST[0:0],link_in_16_TDATA[63:0],link_in_16_TREADY,link_in_16_TLAST[0:0],link_in_17_TDATA[63:0],link_in_17_TREADY,link_in_17_TLAST[0:0],link_in_18_TDATA[63:0],link_in_18_TREADY,link_in_18_TLAST[0:0],link_in_19_TDATA[63:0],link_in_19_TREADY,link_in_19_TLAST[0:0],link_in_20_TDATA[63:0],link_in_20_TREADY,link_in_20_TLAST[0:0],link_in_21_TDATA[63:0],link_in_21_TREADY,link_in_21_TLAST[0:0],link_in_22_TDATA[63:0],link_in_22_TREADY,link_in_22_TLAST[0:0],link_in_23_TDATA[63:0],link_in_23_TREADY,link_in_23_TLAST[0:0],link_in_24_TDATA[63:0],link_in_24_TREADY,link_in_24_TLAST[0:0],link_in_25_TDATA[63:0],link_in_25_TREADY,link_in_25_TLAST[0:0],link_in_26_TDATA[63:0],link_in_26_TREADY,link_in_26_TLAST[0:0],link_in_27_TDATA[63:0],link_in_27_TREADY,link_in_27_TLAST[0:0],link_in_28_TDATA[63:0],link_in_28_TREADY,link_in_28_TLAST[0:0],link_in_29_TDATA[63:0],link_in_29_TREADY,link_in_29_TLAST[0:0],link_in_30_TDATA[63:0],link_in_30_TREADY,link_in_30_TLAST[0:0],link_in_31_TDATA[63:0],link_in_31_TREADY,link_in_31_TLAST[0:0],link_in_32_TDATA[63:0],link_in_32_TREADY,link_in_32_TLAST[0:0],link_in_33_TDATA[63:0],link_in_33_TREADY,link_in_33_TLAST[0:0],link_in_34_TDATA[63:0],link_in_34_TREADY,link_in_34_TLAST[0:0],link_in_35_TDATA[63:0],link_in_35_TREADY,link_in_35_TLAST[0:0],link_in_36_TDATA[63:0],link_in_36_TREADY,link_in_36_TLAST[0:0],link_in_37_TDATA[63:0],link_in_37_TREADY,link_in_37_TLAST[0:0],link_in_38_TDATA[63:0],link_in_38_TREADY,link_in_38_TLAST[0:0],link_in_39_TDATA[63:0],link_in_39_TREADY,link_in_39_TLAST[0:0],link_in_40_TDATA[63:0],link_in_40_TREADY,link_in_40_TLAST[0:0],link_in_41_TDATA[63:0],link_in_41_TREADY,link_in_41_TLAST[0:0],link_in_42_TDATA[63:0],link_in_42_TREADY,link_in_42_TLAST[0:0],link_in_43_TDATA[63:0],link_in_43_TREADY,link_in_43_TLAST[0:0],link_in_44_TDATA[63:0],link_in_44_TREADY,link_in_44_TLAST[0:0],link_in_45_TDATA[63:0],link_in_45_TREADY,link_in_45_TLAST[0:0],link_in_46_TDATA[63:0],link_in_46_TREADY,link_in_46_TLAST[0:0],link_in_47_TDATA[63:0],link_in_47_TREADY,link_in_47_TLAST[0:0],link_out_00_TDATA[63:0],link_out_00_TVALID,link_out_00_TLAST[0:0],link_out_01_TDATA[63:0],link_out_01_TVALID,link_out_01_TLAST[0:0],link_out_02_TDATA[63:0],link_out_02_TVALID,link_out_02_TLAST[0:0],link_out_03_TDATA[63:0],link_out_03_TVALID,link_out_03_TLAST[0:0],link_out_04_TDATA[63:0],link_out_04_TVALID,link_out_04_TLAST[0:0],link_out_05_TDATA[63:0],link_out_05_TVALID,link_out_05_TLAST[0:0],link_out_06_TDATA[63:0],link_out_06_TVALID,link_out_06_TLAST[0:0],link_out_07_TDATA[63:0],link_out_07_TVALID,link_out_07_TLAST[0:0],link_out_08_TDATA[63:0],link_out_08_TVALID,link_out_08_TLAST[0:0],link_out_09_TDATA[63:0],link_out_09_TVALID,link_out_09_TLAST[0:0],link_out_10_TDATA[63:0],link_out_10_TVALID,link_out_10_TLAST[0:0],link_out_11_TDATA[63:0],link_out_11_TVALID,link_out_11_TLAST[0:0],link_out_12_TDATA[63:0],link_out_12_TVALID,link_out_12_TLAST[0:0],link_out_13_TDATA[63:0],link_out_13_TVALID,link_out_13_TLAST[0:0],link_out_14_TDATA[63:0],link_out_14_TVALID,link_out_14_TLAST[0:0],link_out_15_TDATA[63:0],link_out_15_TVALID,link_out_15_TLAST[0:0],link_out_16_TDATA[63:0],link_out_16_TVALID,link_out_16_TLAST[0:0],link_out_17_TDATA[63:0],link_out_17_TVALID,link_out_17_TLAST[0:0],link_out_18_TDATA[63:0],link_out_18_TVALID,link_out_18_TLAST[0:0],link_out_19_TDATA[63:0],link_out_19_TVALID,link_out_19_TLAST[0:0],link_out_20_TDATA[63:0],link_out_20_TVALID,link_out_20_TLAST[0:0],link_out_21_TDATA[63:0],link_out_21_TVALID,link_out_21_TLAST[0:0],link_out_22_TDATA[63:0],link_out_22_TVALID,link_out_22_TLAST[0:0],link_out_23_TDATA[63:0],link_out_23_TVALID,link_out_23_TLAST[0:0],link_out_24_TDATA[63:0],link_out_24_TVALID,link_out_24_TLAST[0:0],link_out_25_TDATA[63:0],link_out_25_TVALID,link_out_25_TLAST[0:0],link_out_26_TDATA[63:0],link_out_26_TVALID,link_out_26_TLAST[0:0],link_out_27_TDATA[63:0],link_out_27_TVALID,link_out_27_TLAST[0:0],link_out_28_TDATA[63:0],link_out_28_TVALID,link_out_28_TLAST[0:0],link_out_29_TDATA[63:0],link_out_29_TVALID,link_out_29_TLAST[0:0],link_out_30_TDATA[63:0],link_out_30_TVALID,link_out_30_TLAST[0:0],link_out_31_TDATA[63:0],link_out_31_TVALID,link_out_31_TLAST[0:0],link_out_32_TDATA[63:0],link_out_32_TVALID,link_out_32_TLAST[0:0],link_out_33_TDATA[63:0],link_out_33_TVALID,link_out_33_TLAST[0:0],link_out_34_TDATA[63:0],link_out_34_TVALID,link_out_34_TLAST[0:0],link_out_35_TDATA[63:0],link_out_35_TVALID,link_out_35_TLAST[0:0],link_out_36_TDATA[63:0],link_out_36_TVALID,link_out_36_TLAST[0:0],link_out_37_TDATA[63:0],link_out_37_TVALID,link_out_37_TLAST[0:0],link_out_38_TDATA[63:0],link_out_38_TVALID,link_out_38_TLAST[0:0],link_out_39_TDATA[63:0],link_out_39_TVALID,link_out_39_TLAST[0:0],link_out_40_TDATA[63:0],link_out_40_TVALID,link_out_40_TLAST[0:0],link_out_41_TDATA[63:0],link_out_41_TVALID,link_out_41_TLAST[0:0],link_out_42_TDATA[63:0],link_out_42_TVALID,link_out_42_TLAST[0:0],link_out_43_TDATA[63:0],link_out_43_TVALID,link_out_43_TLAST[0:0],link_out_44_TDATA[63:0],link_out_44_TVALID,link_out_44_TLAST[0:0],link_out_45_TDATA[63:0],link_out_45_TVALID,link_out_45_TLAST[0:0],link_out_46_TDATA[63:0],link_out_46_TVALID,link_out_46_TLAST[0:0],link_out_47_TDATA[63:0],link_out_47_TVALID,link_out_47_TLAST[0:0]";
begin
end;
