-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mergeClusters1 is
port (
    ap_ready : OUT STD_LOGIC;
    iphi1 : IN STD_LOGIC_VECTOR (2 downto 0);
    icet1 : IN STD_LOGIC_VECTOR (15 downto 0);
    ieta2 : IN STD_LOGIC_VECTOR (2 downto 0);
    iphi2 : IN STD_LOGIC_VECTOR (2 downto 0);
    icet2 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of mergeClusters1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal tmp_s_fu_72_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_78_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_66_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_tmp_s_fu_84_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ieta2_cast_fu_62_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal iphi2_cast2_fu_58_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal cet2_write_assign_fu_92_p3 : STD_LOGIC_VECTOR (15 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= ieta2_cast_fu_62_p1;
    ap_return_1 <= iphi2_cast2_fu_58_p1;
    ap_return_2 <= cet2_write_assign_fu_92_p3;
    cet2_write_assign_fu_92_p3 <= 
        p_tmp_s_fu_84_p3 when (tmp_fu_66_p2(0) = '1') else 
        icet2;
    ieta2_cast_fu_62_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ieta2),16));
    iphi2_cast2_fu_58_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(iphi2),16));
    p_tmp_s_fu_84_p3 <= 
        ap_const_lv16_0 when (tmp_s_fu_72_p2(0) = '1') else 
        tmp_1_fu_78_p2;
    tmp_1_fu_78_p2 <= std_logic_vector(unsigned(icet2) + unsigned(icet1));
    tmp_fu_66_p2 <= "1" when (iphi1 = iphi2) else "0";
    tmp_s_fu_72_p2 <= "1" when (unsigned(icet1) > unsigned(icet2)) else "0";
end behav;
